version: '3'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

## build时，不互相依赖且都tty:true，networks仿真实便于调试
services:
### Workspace Utilities ##################################
    workspace:
      build:
        context: ./workspace
        args:
          - CHANGE_ALPINE_SOURCE=${CHANGE_ALPINE_SOURCE}
      volumes:
        - /data/www:/var/www
      ports:
        - "2222:22"
      tty: true
      networks:
        - frontend
        - backend


### PHP-FPM ##############################################
    php-fpm:
      build:
        context: ./php-fpm
        args:
          - CHANGE_ALPINE_SOURCE=${CHANGE_ALPINE_SOURCE}
      volumes:
        - /data/www:/var/www
      tty: true
      networks:
        - backend


### Redis ################################################
    redis:
      build:
        context: ./redis
        args:
          - CHANGE_ALPINE_SOURCE=${CHANGE_ALPINE_SOURCE}
      volumes:
        - /data/.mydock/redis:/data
      ports:
        - "6379:6379"
      tty: true
      networks:
        - backend


### Caddy Server #########################################
    caddy:
      build:
        context: ./caddy
        args:
          - CHANGE_ALPINE_SOURCE=${CHANGE_ALPINE_SOURCE}
      volumes:
        - /data/www:/var/www
        - /data/logs/caddy:/var/log/caddy
        - /data/.mydock/caddy:/root/.caddy
        - ./caddy/conf:/etc/caddy
      ports:
        - "80:80"
        - "443:443"
      tty: true
      networks:
        - frontend
        - backend

    caddy-builder:
      build:
        context: ./caddy-builder
        args:
          - CHANGE_ALPINE_SOURCE=${CHANGE_ALPINE_SOURCE}
      tty: true


### Certbot ##############################################
    certbot:
      build:
        context: ./certbot
        args:
          - CHANGE_ALPINE_SOURCE=${CHANGE_ALPINE_SOURCE}
      volumes:
        - ./certbot/letsencrypt/:/var/www/letsencrypt
      networks:
        - frontend
