FROM golang:1.10.3-alpine3.7 as builder

ARG CHANGE_ALPINE_SOURCE=true
RUN if [ ${CHANGE_ALPINE_SOURCE} = true ]; then \
    sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/' /etc/apk/repositories \
;fi

# RUN echo "216.239.37.1  golang.org" >> /etc/hosts
# RUN echo "216.239.34.21 godoc.org" >> /etc/hosts

RUN apk update \
    && apk upgrade \
    && apk add --no-cache git

RUN go get github.com/abiosoft/caddyplug/caddyplug

FROM alpine:3.7

LABEL maintainer="Fanybook <fanybook@126.com>"

ARG plugins="git"

COPY --from=builder /go/bin/caddyplug /usr/bin/caddyplug

## If you come frome china, please ues it.

# RUN echo "172.217.6.127 golang.org" >> /etc/hosts

RUN caddyplug install-caddy \
    && caddyplug install ${plugins} \
    && caddy --version

EXPOSE 80 443 2015

WORKDIR /var/www/public

CMD ["/usr/bin/caddy", "-conf", "/etc/Caddyfile"]