FROM php:7.1-fpm-alpine

LABEL maintainer="Fanybook <fanybook@126.com>"

ARG CHANGE_ALPINE_SOURCE=true
RUN if [ ${CHANGE_ALPINE_SOURCE} = true ]; then \
    sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/' /etc/apk/repositories \
;fi

RUN apk update \
    && apk upgrade \
    && apk add --no-cache bash \
    && apk add --no-cache --virtual .build-deps \
    # autoconf \
    build-base \
    # nghttp2 \
    nghttp2-dev \
    libpq \
    # postgresql-dev
    # && apk add --no-cache m4 \
    # && apk add --no-cache gcc \
    # && apk add --no-cache cloog \
    # && apk add --no-cache isl hiredis-dev libmcrypt-dev gmp-dev icu-dev linux-headers musl

###########################################################################
# Swoole EXTENSION
# docker-php-ext-install bcmath

# apk add bzip2-dev
# docker-php-ext-install bz2

# docker-php-ext-install dba

# apk add enchant-dev
# docker-php-ext-install enchant

# docker-php-ext-install exif

# apk add libpng-dev
# docker-php-ext-install gd
# docker-php-ext-install gettext

# apk add gmp-dev
# docker-php-ext-install gmp

# apk add imap-dev
# docker-php-ext-install imap

# apk add icu-dev
# docker-php-ext-install intl

# apk add openldap-dev
# docker-php-ext-install ldap

# apk add libmcrypt-dev
# docker-php-ext-install mcrypt

# docker-php-ext-install mysqli

# apk add unixodbc-dev
# mkdir /usr/local/incl
# cp /usr/include/sqlext.h /usr/local/incl/
# 另一方案 RUN ln -s /usr/include /usr/local/incl
# docker-php-ext-install odbc
RUN set -ex; \
    docker-php-source extract; \
    { \
        echo '# https://github.com/docker-library/php/issues/103#issuecomment-271413933'; \
        echo 'AC_DEFUN([PHP_ALWAYS_SHARED],[])dnl'; \
        echo; \
        cat /usr/src/php/ext/odbc/config.m4; \
    } > temp.m4; \
    mv temp.m4 /usr/src/php/ext/odbc/config.m4; \
    apk add --no-cache unixodbc-dev; \
    docker-php-ext-configure odbc --with-unixODBC=shared,/usr; \
    docker-php-ext-install odbc; \
    docker-php-source delete


# docker-php-ext-install pcntl
# docker-php-ext-install pdo_mysql
# apk add aspell-dev
# docker-php-ext-install pspell
# docker-php-ext-install shmop
# apk add net-snmp-dev
# docker-php-ext-install snmp
# apk add libxml2-dev
# docker-php-ext-install soap
# apk add tidyhtml-dev
# docker-php-ext-install tidy
# docker-php-ext-install wddx
# docker-php-ext-install xmlrpc
# apk add libxslt-dev
# docker-php-ext-install xsl
# docker-php-ext-install opcache
# docker-php-ext-install zip
###########################################################################

ARG INSTALL_SWOOLE=true

RUN if [ ${INSTALL_SWOOLE} = true ]; then \
    # Install Php Swoole Extension
    # apk add hiredis-dev
    wget https://github.com/swoole/swoole-src/archive/v4.0.1.tar.gz \
    && tar -xzvf v4.0.1.tar.gz \
    && cd swoole-src-4.0.1 && \
    && phpize \
    && ./configure --enable-swoole-debug --enable-sockets --enable-openssl --enable-http2 --enable-async-redis --enable-mysqlnd --enable-coroutine-postgresql \
    && make -j$(nproc) \
    && make install \
    && docker-php-ext-enable swoole \
;fi

RUN apk del .build-deps \
    && rm -rf /var/cache/apk/*

CMD ["php-fpm"]

EXPOSE 9000
